# 2. Data Explorations

## Import libraries and load datasets

In [1]:
# Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Load data
df_weather = pd.read_csv('../data/hcmc_weather_data.csv')
df_aq = pd.read_csv('../data/hcmc_air_quality_data.csv')

## 2.1. Data Preprocessing

### Data overview

In [3]:
print("Weather Data Info:")
print(df_weather.info())

Weather Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17544 entries, 0 to 17543
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   date_time                17544 non-null  object
 1   temperature_2m           17544 non-null  float64
 2   relative_humidity_2m     17544 non-null  float64
 3   dew_point_2m             17544 non-null  float64
 4   apparent_temperature     17544 non-null  float64
 5   precipitation            17544 non-null  float64
 6   cloud_cover              17544 non-null  float64
 7   vapour_pressure_deficit  17544 non-null  float64
 8   wind_speed_10m           17544 non-null  float64
 9   wind_direction_10m       17544 non-null  float64
 10  weather_code             17544 non-null  float64
dtypes: float64(10), object(1)
memory usage: 1.5+ MB
None

In [4]:
print("\nAir Quality Data Info:")
print(df_aq.info())

Air Quality Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17544 entries, 0 to 17543
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date_time         17544 non-null  object
 1   pm10              17544 non-null  float64
 2   pm2_5             17544 non-null  float64
 3   carbon_monoxide   17544 non-null  float64
 4   nitrogen_dioxide  17544 non-null  float64
 5   sulphur_dioxide   17544 non-null  float64
 6   ozone             17544 non-null  float64
 7   us_aqi            17544 non-null  float64
dtypes: float64(7), object(1)
memory usage: 1.1+ MB
None

In [5]:
df_weather.head()

,date_time,temperature_2m,relative_humidity_2m,dew_point_2m,apparent_temperature,precipitation,cloud_cover,vapour_pressure_deficit,wind_speed_10m,wind_direction_10m,weather_code
0,2022-10-01 00:00:00+00:00,25.511000,94.49476,24.561,31.543438,1.3,44.700000,0.179606,2.902413,209.74480,61.0
1,2022-10-01 01:00:00+00:00,26.411001,88.26100,24.311,31.320229,0.6,55.500000,0.403905,9.504272,232.69597,53.0
2,2022-10-01 02:00:00+00:00,26.911001,88.03870,24.761,32.211530,0.7,46.200005,0.423807,8.788720,214.99210,53.0
3,2022-10-01 03:00:00+00:00,28.011000,85.29904,25.311,33.920822,0.6,100.000000,0.555415,7.072878,194.74360,53.0
4,2022-10-01 04:00:00+00:00,29.011000,78.12226,24.811,34.491055,0.4,100.000000,0.875935,7.754637,201.80147,51.0

In [6]:
df_aq.head()

,date_time,pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,us_aqi
0,2022-10-01 00:00:00+00:00,61.2,42.1,1123.0,50.80,11.50,4.0,73.652490
1,2022-10-01 01:00:00+00:00,36.9,24.9,906.0,43.05,11.25,14.0,76.471634
2,2022-10-01 02:00:00+00:00,28.0,18.5,598.0,31.95,10.90,27.0,77.597520
3,2022-10-01 03:00:00+00:00,24.2,15.9,281.0,19.70,10.50,48.0,78.182625
4,2022-10-01 04:00:00+00:00,26.0,17.1,213.0,14.25,10.50,67.0,78.430855

In [7]:
# Combine data into one dataframe
df = pd.merge(df_weather, df_aq, on='date_time', how='outer')
df = df.sort_values(by='date_time')
df

,date_time,temperature_2m,relative_humidity_2m,dew_point_2m,apparent_temperature,precipitation,cloud_cover,vapour_pressure_deficit,wind_speed_10m,wind_direction_10m,weather_code,pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,us_aqi
0,2022-10-01 00:00:00+00:00,25.511000,94.494760,24.561000,31.543438,1.3,44.700000,0.179606,2.902413,209.74480,61.0,61.2,42.1,1123.0,50.80,11.50,4.0,73.652490
1,2022-10-01 01:00:00+00:00,26.411001,88.261000,24.311000,31.320229,0.6,55.500000,0.403905,9.504272,232.69597,53.0,36.9,24.9,906.0,43.05,11.25,14.0,76.471634
2,2022-10-01 02:00:00+00:00,26.911001,88.038700,24.761000,32.211530,0.7,46.200005,0.423807,8.788720,214.99210,53.0,28.0,18.5,598.0,31.95,10.90,27.0,77.597520
3,2022-10-01 03:00:00+00:00,28.011000,85.299040,25.311000,33.920822,0.6,100.000000,0.555415,7.072878,194.74360,53.0,24.2,15.9,281.0,19.70,10.50,48.0,78.182625
4,2022-10-01 04:00:00+00:00,29.011000,78.122260,24.811000,34.491055,0.4,100.000000,0.875935,7.754637,201.80147,51.0,26.0,17.1,213.0,14.25,10.50,67.0,78.430855
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17539,2024-09-30 19:00:00+00:00,26.011000,96.791306,25.461000,32.294750,0.0,35.400000,0.107814,5.220000,226.39711,1.0,33.1,22.9,528.0,43.10,36.30,6.0,85.053185
17540,2024-09-30 20:00:00+00:00,25.711000,96.784290,25.161001,31.722473,0.0,34.500000,0.106154,5.720490,204.14554,1.0,30.4,21.1,474.0,40.50,34.40,4.0,82.641846
17541,2024-09-30 21:00:00+00:00,25.561000,96.780716,25.011000,31.509857,0.0,33.600000,0.105334,5.474486,189.46225,1.0,27.6,19.0,433.0,37.70,33.80,4.0,80.824470
17542,2024-09-30 22:00:00+00:00,25.311000,97.936900,24.961000,31.394775,0.0,36.900000,0.066511,4.327493,196.92760,1.0,27.1,18.6,418.0,34.70,36.10,6.0,79.406030
17543,2024-09-30 23:00:00+00:00,25.361000,97.646100,24.961000,31.518940,0.0,23.100000,0.076111,3.818376,188.13002,1.0,28.9,19.7,418.0,31.40,39.80,9.0,78.448580

```markdown
Some tasks should be done before we need to proceed in this phase
1. Since the data contains `17544 non-null entries`, there is no need to handle missing values.
2. If we use `weather_code`, it will confuse the reader and they won't know what type of weather it is, so we will change it to `weather_status`.
3. Detect and handle if having invalid values.
    - `temperature_2m`, `apparent_temperature` at HCMC should be between 10°C and 50°C
    - `relative_humidity_2m` should be between 0% and 100%
    - `precipitation`, `cloud_cover`, `wind_speed_10m`, `pm10`, `pm2_5`, `carbon_monoxide`, `nitrogen_dioxide`, `sulphur_dioxide` and `ozone` should not be negative
4. Check the continuity of time.
5. Detect and handle outliers.
6. Check the validity of the relationship between the variables.
```

### Map `weather_code` to `weather_status`

In [8]:
def map_weather_code(code):
    '''
    Mapping weather code to weather status based on WMO Weather interpretation codes (WW)
    
    -------------
    Parameters:
        code (int): Weather code

    -------------
    Returns:
        str: Weather

    '''
    weather_codes = {
        0: 'Clear Sky',
        1: 'Mainly Clear',
        2: 'Partly Cloudy',
        3: 'Overcast',
        45: 'Foggy',
        48: 'Depositing Rime Fog',
        51: 'Light Drizzle',
        53: 'Moderate Drizzle',
        55: 'Dense Drizzle',
        56: 'Light Freezing Drizzle',
        57: 'Dense Freezing Drizzle',
        61: 'Light Rain',
        63: 'Moderate Rain',
        65: 'Heavy Rain',
        66: 'Light Freezing Rain',
        67: 'Heavy Freezing Rain',
        71: 'Light Snow',
        73: 'Moderate Snow',
        75: 'Heavy Snow',
        77: 'Snow Grains',
        80: 'Light Rain Showers',
        81: 'Moderate Rain Showers',
        82: 'Violent Rain Showers',
        85: 'Light Snow Showers',
        86: 'Heavy Snow Showers',
    }
    return weather_codes.get(code, 'Unknown')

# Map weather code to weather description
df['weather_status'] = df['weather_code'].apply(map_weather_code)
df.drop(columns=['weather_code'], inplace=True)

# Check result
print("Unique weather statuses: ", end='')
print(df['weather_status'].unique())

Unique weather statuses: ['Light Rain' 'Moderate Drizzle' 'Light Drizzle' 'Moderate Rain'
 'Overcast' 'Heavy Rain' 'Dense Drizzle' 'Partly Cloudy' 'Mainly Clear'
 'Clear Sky']

### Detect invalid values

In [9]:
# `temperature_2m`, `apparent_temperature` at HCMC should be between 10°C and 50°C
invalid_values = False

if df['temperature_2m'].min() < 10 or df['temperature_2m'].max() > 50:
    print("Invalid temperature_2m values")
    invalid_values = True
if df['apparent_temperature'].min() < 10 or df['apparent_temperature'].max() > 50:
    print("Invalid apparent_temperature values")
    invalid_values = True

# `relative_humidity_2m` should be between 0% and 100%
if df['relative_humidity_2m'].min() < 0 or df['relative_humidity_2m'].max() > 100:
    print("Invalid relative_humidity_2m values")
    invalid_values = True

# `precipitation`, `cloud_cover`, `wind_speed_10m`, `pm10`, `pm2_5`, `carbon_monoxide`, 
# `nitrogen_dioxide`, `sulphur_dioxide` and `ozone` should not be negative
non_negative_columns = ['precipitation', 'cloud_cover', 'wind_speed_10m', 'pm10', 'pm2_5', 
                        'carbon_monoxide', 'nitrogen_dioxide', 'sulphur_dioxide', 'ozone']
if any(df[non_negative_columns].lt(0).any()):
    print("Invalid negative values")
    invalid_values = True

if not invalid_values:
    print("Valid values")

Valid values

### Check the continuity of time

In [10]:
full_range = pd.date_range(start=df['date_time'].min(), end=df['date_time'].max(), freq='h')
df['date_time'] = pd.to_datetime(df['date_time'])
missing_times = full_range[~full_range.isin(df['date_time'])]

if len(missing_times) == 0:
    print("No missing time")
else:
    print("Missing times:")
    print(missing_times)

No missing time

### Detect and handle outliers

In [11]:
def analyze_outliers(df, columns):
    '''
    Analyzes outliers using the IQR method.
    
    -------------
    Parameters:
        df (pandas.DataFrame): The DataFrame containing the data to analyze.
        columns (list of str): The list of column names to check for outliers.
    
    -------------
    Returns:
        dict: A dictionary where keys are column names and values are lists of outlier values.
    '''
    outlier_info = {}

    for column in columns:
        Q1 = df[column].quantile(0.25)
        Q3 = df[column].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR

        outliers = df[(df[column] < lower_bound) | (df[column] > upper_bound)][column]

        outlier_info[column] = {
            'total_outliers': len(outliers),
            'percentage': (len(outliers) / len(df)) * 100,
            'min': outliers.min() if len(outliers) > 0 else None,
            'max': outliers.max() if len(outliers) > 0 else None
        }
    
    return outlier_info

# Analyze outliers
df_numeric = df.select_dtypes(include=[np.number])
outlier_info = analyze_outliers(df_numeric, df_numeric.columns)

print("Outlier Information:")
for column, info in outlier_info.items():
    print(f"\tOutliers in {column}:")
    print(f"\tTotal outliers: {info['total_outliers']} ({info['percentage']:.2f}%)")
    print(f"\tMin: {info['min']}")
    print(f"\tMax: {info['max']}")
    print()

Outlier Information:
	Outliers in temperature_2m:
	Total outliers: 185 (1.05%)
	Min: 18.561
	Max: 39.161

	Outliers in relative_humidity_2m:
	Total outliers: 160 (0.91%)
	Min: 23.241114
	Max: 33.972218

	Outliers in dew_point_2m:
	Total outliers: 738 (4.21%)
	Min: 10.461
	Max: 17.561

	Outliers in apparent_temperature:
	Total outliers: 272 (1.55%)
	Min: 18.859638
	Max: 43.563644

	Outliers in precipitation:
	Total outliers: 2183 (12.44%)
	Min: 0.3
	Max: 21.4

	Outliers in cloud_cover:
	Total outliers: 1425 (8.12%)
	Min: 95.7
	Max: 100.0

	Outliers in vapour_pressure_deficit:
	Total outliers: 1085 (6.18%)
	Min: 2.762848
	Max: 5.4103785

	Outliers in wind_speed_10m:
	Total outliers: 222 (1.27%)
	Min: 21.028437
	Max: 30.085318

	Outliers in wind_direction_10m:
	Total outliers: 0 (0.00%)
	Min: None
	Max: None

	Outliers in pm10:
	Total outliers: 530 (3.02%)
	Min: 75.0
	Max: 158.8

	Outliers in pm2_5:
	Total outliers: 545 (3.11%)
	Min: 51.1
	Max: 110.6

	Outliers in carbon_monoxide:
	Total outliers: 703 (4.01%)
	Min: 977.0
	Max: 3149.0

	Outliers in nitrogen_dioxide:
	Total outliers: 384 (2.19%)
	Min: 73.0
	Max: 170.35

	Outliers in sulphur_dioxide:
	Total outliers: 402 (2.29%)
	Min: 56.6
	Max: 94.2

	Outliers in ozone:
	Total outliers: 174 (0.99%)
	Min: 168.0
	Max: 272.0

	Outliers in us_aqi:
	Total outliers: 386 (2.20%)
	Min: 4.0197897
	Max: 152.13597

```markdown
Based on the above outliers, I suggest that we should split into 2 groups
    - Keeped outliers:
        + `precipitation`   : High precipitation is a real natural phenomenon
        + `cloud_cover`     : Cloud cover of 95-100% is normal',
        + `wind_speed_10m`  : 'Strong winds are a real weather phenomenon',
        + `pm10`            : 'High air pollution is a real phenomenon',
        + `pm2_5`           : 'High air pollution is a real phenomenon',
        + `carbon_monoxide` : 'High CO levels may be due to actual pollution',
        + `nitrogen_dioxide`: 'High NO2 levels may be due to actual pollution',
        + `ozone`           : 'High ozone levels may be due to actual weather conditions'
    - Handled outliers:
        + the others
```

In [12]:
def handle_outliers(df, columns_handle, method='iqr'):
    '''
    Handles outliers in specified columns of a DataFrame using the specified method.

    -------------
    Parameters:
        df (pandas.DataFrame): The input DataFrame.
        columns_handle (list): List of column names to handle outliers for.
        method (str): The method to use for handling outliers. 
                    Options are 'iqr' (Interquartile Range) and 'percentile'. 
                    Default is 'iqr'.
                
    -------------
    Returns:
        pandas.DataFrame: A DataFrame with outliers handled in the specified columns.
    '''
    df_cleaned = df.copy()

    for column in columns_handle:
        Q1 = df[column].quantile(0.25)
        Q3 = df[column].quantile(0.75)
        IQR = Q3 - Q1
        
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR

        if method == 'iqr':
            df_cleaned[column] = df_cleaned[column].clip(lower_bound, upper_bound)
        elif method == 'percentile':
            # using percentile 5 and 95
            lower_bound = df[column].quantile(0.05)
            upper_bound = df[column].quantile(0.95)
            df_cleaned[column] = df_cleaned[column].clip(lower_bound, upper_bound)

    return df_cleaned

# Handle outliers
columns_to_handle = {
    'temperature_2m': 'percentile', 
    'relative_humidity_2m': 'iqr',
    'dew_point_2m': 'iqr',
    'apparent_temperature': 'percentile',
    'vapour_pressure_deficit': 'iqr',
    'sulphur_dioxide': 'iqr',
    'us_aqi': 'iqr'
}

df_cleaned = handle_outliers(df, columns_to_handle.keys(), method='iqr')

### Check the validity of the relationship between the variables

In [13]:
def check_data_relationships(df):
    '''
    Checks relationships between columns in the DataFrame.

    -------------
    Parameters:
        df (pandas.DataFrame): The input DataFrame.

    -------------
    Returns:
        list: A list of issues found in the data.
    '''
    issues = []

    # Check temperature_2m and dew_point_2m
    if 'temperature_2m' in df.columns and 'dew_point_2m' in df.columns:
        if any(df['dew_point_2m'] > df['temperature_2m']):
            issues.append("Dew point temperature is greater than air temperature")
        
    # Check cloud_cover and precipitation
    if 'cloud_cover' in df.columns and 'precipitation' in df.columns:
        if any((df['cloud_cover'] == 0) & (df['precipitation'] > 0)):
            issues.append("Cloud cover is 0 but there is precipitation")

    return issues

# Check data relationships
relationship_issues = check_data_relationships(df_cleaned)
print("Relationship Issues:", relationship_issues)

Relationship Issues: []

### Check constraints of project and save to file

In [14]:
# Check constraints
assert df.shape[1] >= 5 and df.shape[0] >= 1000, "Data does not meet the constraints"
print("Data meets the constraints")
print(f"Number of attributes: {df.shape[1]}")
print(f"Number of records: {df.shape[0]}")

Data meets the constraints
Number of attributes: 18
Number of records: 17544

### Change timezone to UTC+7 (HoChiMinh)

In [15]:
def change_timezone(data):
    data_datetime = pd.to_datetime(data['date_time'], utc=True)
    data_datetime = data_datetime.dt.tz_convert('Asia/Ho_Chi_Minh')
    data_datetime = data_datetime.dt.tz_localize(None)
    data['date_time'] = data_datetime
    return data

df_cleaned = change_timezone(df_cleaned)

### Save cleaned data

In [16]:
# Save cleaned data
df_cleaned.to_csv('../data/clean_hcmc_waq.csv', index=False)